# Generated by Django 6.0 on 2026-01-04 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('THEORY', 'Essay')])),
                ('text', models.TextField()),
                ('expected_answer', models.TextField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position', models.PositiveIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'unique_together': {('position', 'exam')},
            },
        ),
    ]
