# Generated by Django 6.0 on 2026-01-04 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('year', models.SmallIntegerField(default=2026)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
